version: "2"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5555:5555"
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
#   database:
#     build: ./database
